name: Build & Upload Artifact
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Install Dependencies
        run: bun install

      - name: Build Revenge
        run: bun run build -- --minify

      - name: Upload revenge.min.js
        uses: actions/upload-artifact@v4
        with:
          name: revenge-min
          path: ./dist/revenge.min.js

      - name: Upload revenge.js
        uses: actions/upload-artifact@v4
        with:
          name: revenge
          path: ./dist/revenge.js
